import React from "react";
import "./Projects.css";
import SectionHeading from "../SectionHeading/SectionHeading";
import ProjectItem from "../ProjectItem/ProjectItem";

const Projects = ({setNavbarVisible}) => {
  return (
    <div className="wrapper" id="projects">
      <div id="cheating">
        <SectionHeading preh2="My work" heading="Projects." />
      </div>

      <div className="project_container">
        {/* <ProjectItem
          title="Fake Reddit"
          description="Forum web application, inspired by Reddit. This platform allows users to create topic-specific categories, make posts, and like posts from others. Users must sign up and log in to access all features. Part of the IDG 2001 Cloud Technologies course."
          insideProjectDesc = "This platform allows users to create topic-specific categories, make posts, and like posts from others. Users must sign up and log in to access all features. The application was developed using a MySQL database, Flask for the API, and React for the frontend. All components are deployed in Docker containers via Docker Compose on a Chameleon Cloud virtual machine."
          img="/img/fakereddit.png"
          technologies={["/img/react.svg", "/img/python.png", "/img/mysql.png", "/img/chameleoncloud.png", "/img/docker.png"]}
          githubCode="https://github.com/AndrChr0/cloud-assignment-2"
          liveSite="http://129.114.27.140/"
          workFormat="/img/group.png"
          insideProjectImg = {['/img/fakereddit.png','/img/fakereddit_1.png', '/img/fakereddit_2.png', '/img/fakereddit_3.png', '/img/fakereddit_4.png', '/img/fakereddit_5.png', '/img/fakereddit_6.png']}
          contributors = {['Ola Nikolai Skjeret', 'Andreas Christiansen']}
          setNavbarVisible={setNavbarVisible}
        /> */}

        <ProjectItem
          title="smArt"
          description="smArt is an interactive art exhibition. The system allows the user to choose an art style and take a picture of themselves, and based on that, have a personal work of art generated using artificial intelligence."
          insideProjectDesc = "smArt Gallery is an interactive art exhibition developed as part of the course IDG3006 - Web of Things. The project was carried out in collaboration between three web developers and three interaction designers. The system allows the user to choose an art style and take a picture of themselves, and based on that, have a personal work of art generated using artificial intelligence."
          img="/img/smArt.png"
          technologies={["img/mongodb.webp", "img/express.png" , "img/react.svg", "/img/nodejs.webp", "img/tailwind.png", "img/typescript.png", "img/openai.svg"]}
          githubCode=""
          liveSite=""
          workFormat="/img/group.png"
          contributors = {['Andreas Christiansen', 'Ola Nikolai Skjeret', 'Jakob Wergeland Putkowski', 'Hedda Saasen Undseth', 'Charlotte Skramestø']}
          contributorLink= {["https://www.achr.no/", "https://ninejar.github.io/portfolio/", "https://jakobwergeland.myportfolio.com/", "https://saasen.framer.website/", "https://charlotteskramesto.no/"]}
          insideProjectImg = {["/img/carousel_smart_1.png", "/img/carousel_smart_2.png", "/img/carousel_smart_3.png", "/img/carousel_smart_4.png"]}
          insideProjectImgCaption = {["Select an art style using the remote", "Snap a picture of yourself", "See yourself in the selected art style – generated by AI", "Then the image is sent to a gallery!"]}
          setNavbarVisible={setNavbarVisible}
          processHeadings={["Ideation and Concept", "Implementation", "Results"]}
          processDescriptions={["At the start of the project, we had multiple ideas including a smart mirror, an assistive living system, and a WoT-based well-being concept. One idea that stood out was an interactive art exhibition using emotion detection, where the visuals and audios would react to facial expressions. This concept then evolved into our final direction: smArt – which is an AI-powered art installation that provides a fun, easy and interactive way to experience and learn about art.", "I was mainly responsible for front-end development. I implemented most of the UI design provided by the UX team, and features such as art style selection and photo-capture. I also added music and sound effects based on system states. Something I'm proud of was integrating a WebSocket-based control interface, so users can interact with the system in real time with a remote. This helped tie the project directly to core WoT principles.", "The final prototype allowed users to select an art style of their choice, take a picture of themselves then see themselves in that art style with the help with OpenAI's API. "]}
          processImages={[ "/img/smart_process_1.png","/img/smart_process_2.png","/img/smart_process_3.png"]}
        />

        <ProjectItem
          title="LAiLA, The AI-Driven Assessor"
          description="As part of my bachelor's thesis, my group and I designed and developed LAiLA. By utilizing AI, the system's goal is to effectivize feedback processes in student-dense programming courses."
          insideProjectDesc = "As part of my bachelor's thesis, my group and I designed and developed LAiLA. By utilizing AI, the system's goal is to effectivize feedback processes in student-dense programming courses."
          img="/img/laila.png"
          technologies={["/img/nodejs.webp", "/img/express.png", "/img/mysql.png", "/img/react.svg", "/img/tailwind.png"]}
          githubCode=""
          liveSite=""
          workFormat="/img/group.png"
          contributors = {['Andreas Christiansen', 'Ola Nikolai Skjeret']}
          contributorLink= {["https://www.achr.no/", "https://ninejar.github.io/portfolio/"]}
          insideProjectImg = {["/img/carousel_laila_1.png", "/img/carousel_laila_2.png", "/img/carousel_laila_3.png", "/img/carousel_laila_4.png", "/img/carousel_laila_5.png"]}
          insideProjectImgCaption = {["Lecturer interface: Assignment creation. Set title, description, and deadline etc. Additionally, set criteria for LAiLA to assess.", "Student interface: Get instant feedback on your submission. The results are preliminary, and can resubmit the amount of times the lecturer allows for the assignment.", "Lecturer interface: Report over students' submissions. Includes meta datas such as pass rate, the common problems and strong areas. Based on these data, the lecturer gets suggestions for how to improve the course.", "Lecturer interface: The lecturer has the final say in the assessment. They can approve or reject the AI's comments and add their own. All sections must be reviewed and mark as approved before sending the final feedback back to the student.", "Student interface: The final feedback is sent back to the student. They can see the AI's/lecturer's comments and the final grade."]}
          setNavbarVisible={setNavbarVisible}
          processHeadings={["Insights", "Design", "Development", "Testing"]}
          processDescriptions={["To gather insights for the project, we did desk research on the topic, and then conducted interviews with 21 lecturers across six universities in Norway, in addition to a survey with 76 students enrolled at NTNU. Key insights were perceived benefits and challenges of using AI in education, as well as how to effectively integrate it into the feedback process.", "Based on the insights gathered, we created a System Requirements Document, followed by user stories and acceptance criteria. We then designed the system's architecture and database structure, as well as interfaces for our system's roles: lecturers and students.", "The system was developed using Node.js, Express, MySQL, React, with Tailwind CSS for styling and Claude sonnet 3.7 for the AI. We ended up with a minimum viable product, which includes the core functionalites of the system (AI preliminary feedback, report generation and assisted AI final assessment) and a sufficient interface for both lecturer and student.", "We also conducted testing of the system with both students and lecturers. The tests involved a combination of usability testing of the UI/UX and comparison testing of the AI's feedback against a real world assessment. The results were positive, with the system being perceived as user-friendly and the AI's feedback being relatively accurate, as well as solving the problem of time-consuming feedback processes."]}
          processImages={["/img/process_laila_1.png", "/img/process_laila_2.png", "/img/process_laila_3.png", "/img/process_laila_4.png"]}
        />

        <ProjectItem
          title="Meeting Room Booking System"
          description="During my internship at Kodeo AS, I was responsible for developing a web-based system for reserving meeting rooms for a client."
          insideProjectDesc = "During my internship at Kodeo AS, I was responsible for developing a web-based system for reserving meeting rooms. The system allows administrators to view available times, book rooms, and manage guests and existing reservations. On another user interface, guests can register their visit, as well as view information about the room and time of the meeting. They will then receive a link by email that allows them to unregister their visit after it has been completed. The system is developed with Laravel and MySQL."
          img="/img/booking.png"
          technologies={["/img/laravel.png", "img/mysql.png"]}
          githubCode=""
          liveSite=""
          workFormat="/img/solo.png"
          insideProjectImg = {["/img/carousel_booking_1.png", "/img/carousel_booking_2.png", "/img/carousel_booking_3.png", "/img/carousel_booking_4.png", "/img/carousel_booking_5.png"]}
          insideProjectImgCaption = {["Admin interface: Homepage", "Admin interface: Add a user", "Admin interface: Add a reservation", "Guest interface: Enter email or phone number to get reservation", "Guest interface: Example of a reservation"]}
          setNavbarVisible={setNavbarVisible}
          processHeadings={["Planning and Designing", "Development", "Finished Product"]}
          processDescriptions={["As the core requirements of the system already were pre-defined before handing me the responsibility for developing the project, I started the process by planning and designing the system’s layout and database structure. I focused on clearly separating admin and guest user interface as well as their functionalities, and structuring the relationships between the different entities in the database.", "Utilizing Laravel and MySQL as the tech stack, I developed the system with security (authentication & authorization), usability, and scalability in mind. The Administrators can view available times, book meeting rooms, register guests, and manage existing reservations. The Guests can sign into meetings via their own interface, access meeting details, and receive an email link to cancel their registration after the meeting.", "After development, the system was handed over to the client for use. The guest interface was set up on a tablet in their reception area, allowing guests to easily register their visit. The administrative interface was made available for internal staff to manage rooms, guests, and reservations. Although I worked alone on this project, I received good guidance from the team at Kodeo AS, which helped me improve my skills in Laravel and managing project."]}
          processImages={[ "/img/booking_process_ERD.png", "/img/booking_process_code.png", "/img/booking_process_final.png"]}
        />
        <ProjectItem
          title="Fully Accessible Website"
          description="As part of a Web Accessibility, Usability and Ethics course, I developed a fully accessible (concept) website for my mom's music lesson school. This website is accessible for users with visual, hearing and mobility impairments."
          insideProjectDesc = "As part of a Web Accessibility, Usability and Ethics course, I developed a fully accessible (concept) website for my mom's music lesson school. This website is accessible for users with visual, hearing and mobility impairments."
          img="/img/lisas.png"
          technologies={["/img/html.png", "/img/css.webp", "/img/javascript.png"]}
          githubCode="https://github.com/chriistopherngo/course-project"
          liveSite="https://chriistopherngo.github.io/course-project/"
          workFormat="/img/solo.png"
          insideProjectImg = {["/img/lisas.png", "/img/carousel_accessibility_2.png", "/img/carousel_accessibility_3.png"]}
          insideProjectImgCaption = {["Homepage", "Teachers page", "Call to action"]}
          setNavbarVisible={setNavbarVisible}
          processHeadings={["LoFi", "HiFi", "Development and Final Product"]}
          processDescriptions={["Using Figma, i made a low-fidelity representation of the website's design. Here I focused on the structure of the contents, while having various type of impaired users in mind.", "In this stage I made a high-fidelity representation of the website's design, which is a iterated version of the LoFi. While the structure of contents was the focus in last the stage, the design in terms of colors, typography and reworking placements of elements was the focus of this.", "The final version of the website was developed using HTML, CSS, and JavaScript. To help visually impaired users, I used the ARIA attributes to support screen readers. Users with mobility impairments can navigate through the site with keyboard, and hearing impairments was taken into accounts by adding subtitles in videoes. The website is also responsive and works on all devices. "]}
          processImages={[ "/img/accessibility_process_lofi.png", "/img/accessibility_process_hifi.png", "/img/lisas.png"]}
        />





        {/* <ProjectItem
          title="Scrollytelling Project"
          description="The website is based on the United Nations' Sustainable Development Goal 7, which is to ensure access to affordable, reliable, sustainable, and modern energy for all. Through an engaging and interactive storytelling format, the project aims to raise awareness about the importance of clean and affordable energy and inspire people to take action towards achieving this goal."
          insideProjectDesc ="The website is based on the United Nations' Sustainable Development Goal 7, which is to ensure access to affordable, reliable, sustainable, and modern energy for all. Through an engaging and interactive storytelling format, the project aims to raise awareness about the importance of clean and affordable energy and inspire people to take action towards achieving this goal."
          img="/img/scrollytelling.png"
          technologies={["/img/html.png", "/img/sass.png", "/img/javascript.png"]}
          githubCode="https://github.com/AdvancedCSS2023/assignment-3--scrollytelling-group_2"
          liveSite="https://advancedcss2023.github.io/assignment-3--scrollytelling-group_2/"
          workFormat="/img/group.png"
          insideProjectImg ={[]}
          contributors = {['Shnizana Korolova', 'Edgar Dahl']}
          setNavbarVisible={setNavbarVisible}
        />
        <ProjectItem
          title="The SUPER Assessor"
          description="Exam project in IDG2100 - Full-stack web development. The SUPER Assessor Interface empowers educators to create and manage assessment methods through an interactive card game. It facilitates collaboration by allowing educators to save, review, and share their assessment schemes for feedback. Administrators can manage content and user accounts through a dashboard, streamlining the assessment process and boosting creativity in education."
          insideProjectDesc ="Exam project in IDG2100 - Full-stack web development. The SUPER Assessor Interface empowers educators to create and manage assessment methods through an interactive card game. It facilitates collaboration by allowing educators to save, review, and share their assessment schemes for feedback. Administrators can manage content and user accounts through a dashboard, streamlining the assessment process and boosting creativity in education."
          img="/img/thesuperassessor.png"
          technologies={["/img/mongodb.webp", "/img/express.png", "/img/react.svg", "/img/nodejs.webp",]}
          githubCode="https://github.com/ntnu-design/idg2100-2024-exam-achrolansk"
          workFormat="/img/group.png"
          insideProjectImg ={[]}
          contributors = {['Andreas Christiansen', 'Ola Nikolai Skjeret']}
          setNavbarVisible={setNavbarVisible}
         
        />
        <ProjectItem
          title="Sustainability Diary"
          description="The Digital Sustainability Diary helps students engage with the UN's 17 sustainability goals by journaling their daily activities and reflections. It encourages students to explore how their actions align with these goals, promoting personal growth and a deeper understanding of sustainability. Teachers are the ones to make the tasks. Part of the IDG2671 - Web Project course."
          insideProjectDesc="The Digital Sustainability Diary helps students engage with the UN's 17 sustainability goals by journaling their daily activities and reflections. It encourages students to explore how their actions align with these goals, promoting personal growth and a deeper understanding of sustainability. Teachers are the ones to make the tasks. Part of the IDG2671 - Web Project course."
          img="/img/journals.png"
          technologies={["/img/mongodb.webp", "/img/express.png", "/img/react.svg", "/img/nodejs.webp", "/img/docker.png", "/img/dockercompose.png"]}
          githubCode="https://github.com/Ninejar/cautious-adventure"
          liveSite="https://team1.sustainability.it.ntnu.no/"
          workFormat="/img/group.png"
          insideProjectImg ={[]}
          contributors = {['Ola Nikolai Skjeret', 'Jørgen Nonstad', 'Solveig Ranøien Engen']}
          setNavbarVisible={setNavbarVisible}
        />
        <ProjectItem
          title="CSS Game"
          description="You're a mouse on a mission, slipping past cats as you navigate your way to the cheese. Made through the course IDG1293 - Advanced CSS."
          insideProjectDesc ="You're a mouse on a mission, slipping past cats as you navigate your way to the cheese. Made through the course IDG1293 - Advanced CSS."
          img="/img/mousegame.png"
          technologies={["/img/html.png", "/img/sass.png"]}
          githubCode="https://github.com/AdvancedCSS2023/assignment-2---css-games-group_2"
          liveSite="https://advancedcss2023.github.io/assignment-2---css-games-group_2/"
          workFormat="/img/group.png"
          insideProjectImg ={[]}
          contributors = {['Shnizana Korolova', 'Edgar Dahl']}
          setNavbarVisible={setNavbarVisible}
        /> */}
      </div>
    </div>
  );
};

export default Projects;
